# Generated by Django 6.0.3 on 2026-03-20 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('lastname', models.TextField(verbose_name='Отчество')),
                ('speciality', models.TextField(verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='Дата приёма')),
                ('reservation_time_start', models.TimeField(verbose_name='Начало временного слота')),
                ('reservation_time_end', models.TimeField(verbose_name='Конец временного слота')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Расписание врача',
                'verbose_name_plural': 'Расписания врачей',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('lastname', models.TextField(verbose_name='Отчество')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Reserved', 'Забронирована'), ('Awaiting Confirmation', 'Ожидает подтверждения'), ('Confirmed', 'Подтверждена'), ('Cancelled', 'Отменена')], verbose_name='Статус')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic.patient', verbose_name='Пациент')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic.doctorschedule', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Запись к врачу',
                'verbose_name_plural': 'Записи к врачам',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_datetime', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('status', models.TextField(choices=[('Reserved', 'Уведомление о создании записи'), ('Awaiting Confirmation', 'Уведомление о необходимости подтверждения записи'), ('Confirmed', 'Уведомление о подтверждении записи'), ('Cancelled', 'Уведомление об отмене записи')], verbose_name='Статус')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental_clinic.reservation', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
