# Generated by Django 6.0.3 on 2026-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.TextField(choices=[('Reserved', 'Уведомление о создании записи'), ('Awaiting Confirmation', 'Уведомление о необходимости подтверждения записи'), ('Confirmed', 'Уведомление о подтверждении записи'), ('Cancelled', 'Уведомление об отмене записи')], default='Reserved', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.TextField(choices=[('Reserved', 'Забронирована'), ('Awaiting Confirmation', 'Ожидает подтверждения'), ('Confirmed', 'Подтверждена'), ('Cancelled', 'Отменена'), ('Completed', 'Завершена')], verbose_name='Статус'),
        ),
    ]
